server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/bookdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: sdfgtb123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: LIBRARY-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}

jwt:
  secret: mySecretKey