server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  cloud:
    gateway:
      routes:
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: BOOK-SERVICE
                fallbackuri: forward:/orderServiceFallBack
        - id: LIBRARY-SERVICE
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/library/loans/**
          filters:
            - name: CircuitBreaker
              args:
                name: LIBRARY-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/authenticate/**
          filters:
            - name: CircuitBreaker
              args:
                name: AUTH-SERVICE
                fallbackuri: forward:/productServiceFallBack

logging:
  level:
    org.springframework: DEBUG

jwt:
  secret: mySecretKey